version: 2
jobs:
  build:
    branches:
      ignore:
        - gh-pages
        - /feature-.*/
    docker:
      - image: "circleci/node:12"
    steps:
      - checkout
      # - restore_cache:
      #     key: dependency-cache-{{ checksum "examples/vue/package.json" }}

      # - restore_cache:
      #     key: dependency-cache-{{ checksum "package-lock.json" }}

      - run:
          # Replace typedoc's typescript dep with currently installed version
          # because it comes with an incompatible version
          name: install
          command: |
            npm install

            rm -rf ./node_modules/typedoc/node_modules/typescript
            cp -r ./node_modules/typescript ./node_modules/typedoc/node_modules/typescript
      - run:
          name: test
          command: npm run test:prod && npm run build

      - run:
          name: build-docs
          command: npm run build:docs && npm run build:storybooks:prepare && npm run build:storybooks
      - run: npm run coverage
      - run: npm run deploy-docs
      # - run: git describe --exact-match --tags HEAD && npm run docs && npm run deploy-docs
      - run:
          name: release
          command: npm run semantic-release || true
      # - save_cache:
      #     key: dependency-cache-{{ checksum "package-lock.json" }}
      #     paths:
      #       - ./node_modules
      # - save_cache:
      #     key: dependency-cache-{{ checksum "examples/vue/package.json" }}
      #     paths:
      #       - ./examples/vue/node_modules
